on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Build LaTeX document

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: remove fontspecs
        run: |
          python remove_fonts.py books/jocelin_cronica/main.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: books/jocelin_cronica/
          root_file: main.tex
          latexmk_use_lualatex: true
